apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  PROJECT_NAME: RnVsbCBTdGFjayBGYXN0QVBJIFByb2plY3Q=          # Full Stack FastAPI Project
  FIRST_SUPERUSER: YWRtaW5AZXhhbXBsZS5jb20=                    # admin@example.com
  FIRST_SUPERUSER_PASSWORD: Y2hhbmdldGhpcw==                   # changethis

