apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: azzouz953/backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_SERVER
              value: "db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            - name: PROJECT_NAME
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: PROJECT_NAME
            - name: FIRST_SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: FIRST_SUPERUSER
            - name: FIRST_SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: FIRST_SUPERUSER_PASSWORD

