apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=            # Remplace par l'utilisateur encodé en base64
  POSTGRES_PASSWORD: Ym9kb2xvZ28=    # Remplace par le mot de passe encodé en base64
  POSTGRES_DB: YXBw                      # Remplace par le nom de la base de données encodé en base64
