apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  PROJECT_NAME: {{ .Values.app.projectName | b64enc }}
  FIRST_SUPERUSER: {{ .Values.app.firstSuperuser | b64enc }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.app.firstSuperuserPassword | b64enc }}

