apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: {{ .Values.image.repository }}
          ports:
            - containerPort: 8080

